#pragma once 

enum Spells {
	ATTACK_SPELL_METEOR = 1,
	ATTACK_SPELL_FREEZ = 2,
	ATTACK_SPELL_DRAKONIFORSL = 3,
	MANA_REGENERATE_SPELL_SOUL_HEAL= 4,
	MANA_REGENERATE_SPELL_MIND_HEAL = 5,
	MANA_REGENERATE_SPELL_FEITH_HEAL = 6,
	HP_REGENERATE_SPELL_HEAL_WOUNDS = 7,
	HP_REGENERATE_SPELL_ARMOR_HEAL = 8,
	HP_REGENERATE_SPELL_HEAL_RECUPERATION = 9
};

